open-broker/specification

spec.md
This closes #7 
This adds loan purpose information
=> Add loan purpose information

spec.md
This PR specifies a means for identifying the relaying broker & its identifier.
This closes #4
=> Add broker identification and references

spec.md
=> Adding fields for citizenship/residence, housingCost & bankAccount

spec.md
=> add address information

spec.md
This is just a suggestion but closes  #6
=> Suggestion on how to handle phone-numbers

spec.md
=> Feature loanresult

spec.md
=> Extends employment statuses as discused in #10

terms.md
This is  a bit bare-bones please fill in the @will @williamhogman and also suggest more terms
=> Terms and definitions

spec.md
=> Add status updates and disbursion notification

schema/se/PrivateUnsecuredLoanDelayedProcessing.yaml
=> Delayreason: HOLIDAY -> BANK_HOLIDAY

build_schema.sh, schema-docs/BankAccount.md, schema-docs/PrivateUnsecuredLoanApplicationCreated.md, schema-docs/PrivateUnsecuredLoanOfferAccepted.md, schema-docs/PrivateUnsecuredLoanOfferRejected.md, schema-docs/PrivateUnsecuredLoanOffering.md, schema-docs/README.md, schema/se/BankAccount.yaml, schema/se/PrivateUnsecuredLoanApplicationCreated.yaml, schema/se/PrivateUnsecuredLoanOfferAccepted.yaml, schema/se/PrivateUnsecuredLoanOfferRejected.yaml, schema/se/PrivateUnsecuredLoanOffering.yaml, spec.md
=> Allow accepting and declining offers

schema-docs/PrivateUnsecuredLoanOffering.md
=> Add description for interest rates

schema/se/PrivateUnsecuredLoanApplicationCreated.yaml
`refinanceAmount <= loanAmount` (but description says `refinanceAmount < loanAmount`)
=> Update description of refinanceAmount

schema/se/PrivateUnsecuredLoanApplicationCreated.yaml
This will make them occur grouped together, in a more logic order.
=> Move properties for employment data and child data

schema/se/PrivateUnsecuredLoanOffering.yaml
Possible values are ANNUITY and FIXED_LINE. Descriptions still needs to be done.
=> Add property "amortisationType"

schema/se/PrivateUnsecuredLoanOffering.yaml
Updated description (do not use this if we will switch ineterest rates defines in integers instead).
=> Update description in defintion for interest rates in scema

example/se/PrivateUnsecuredLoanApplicationCreated.json, example/se/PrivateUnsecuredLoanDelayedProcessing.json, example/se/PrivateUnsecuredLoanDisbursed.json, example/se/PrivateUnsecuredLoanOfferAccepted.json, example/se/PrivateUnsecuredLoanOfferRejected.json, example/se/PrivateUnsecuredLoanOffering.json, example/se/PrivateUnsecuredLoanRejection.json, example/se/PrivateUnsecuredLoanStatusUpdated.json
Would like to add example json for all events. So when you are testing your implementation you have some json structure to fall back on.
=> Adds json example for all events

.circleci/config.yml, .circleci/yaml2json.sh
Will fail a build if it is not a valid JSON schema
=> Add CircleCI build script

.gitignore, se/PrivateUnsecuredLoan/README.md, se/PrivateUnsecuredLoan/example/PrivateUnsecuredLoanApplicationCreated.json, se/PrivateUnsecuredLoan/schema/PrivateUnsecuredLoanApplicationCreated.yaml
There are some banks that need to be able to identify which lenders a customer has.
=> Adds bank name to private unsecured loan

no/Mortgage/v0/example/MortgageApplicationCreated_Required.json, no/Mortgage/v0/example/MortgageApplicationRejection.json, no/Mortgage/v0/example/MortgageMessage.json, no/Mortgage/v0/example/MortgageOfferRejected.json
Also corrected some event types to have country code NO
=> Add example for ApplicationCreated with only required fields

se/Mortgage/v0/example/MortgageApplicationCreated.json
1. Still hade old format for paymentRemark(s), where it was an integer instead of a boolean. This is fixed now.
2. Changed indenting in extensions data that was off.
=> Mortgage SE: JSON Exmaple Updates

se/PrivateUnsecuredLoan/README.md, se/PrivateUnsecuredLoan/schema/PrivateUnsecuredLoanMessage.yaml
We need a more generic way of sending information from bank to the broker.
=> Adds message to sweden specification

se/PrivateUnsecuredLoan/README.md
=> Fix links in swedens readme file

no/PrivateUnsecuredLoan/schema/PrivateUnsecuredLoanApplicationCreated.yaml
This adds value for "permittering".
=> Add value for temporarily discharged employee in Norway

CHANGELOG.md, CODEOWNERS, se/PrivateUnsecuredLoan/schema/BankAccount.yaml
=> Update clearing num format

no/PrivateUnsecuredLoan/example/PrivateUnsecuredLoanOfferAccepted.json, se/PrivateUnsecuredLoan/example/PrivateUnsecuredLoanOfferAccepted.json, se/PrivateUnsecuredLoan/schema/PrivateUnsecuredLoanOfferAccepted.yaml
Adding 'bankName' field to OfferAccepted cloud event to fullfill requirements to provide bank name for bank account.
=> Bank name accept

no/PrivateUnsecuredLoan/example/PrivateUnsecuredLoanApplicationCreated.json, se/PrivateUnsecuredLoan/example/PrivateUnsecuredLoanApplicationCreated.json, se/PrivateUnsecuredLoan/schema/PrivateUnsecuredLoanApplicationCreated.yaml
We got a requirement to add a property 'refinanceAmount' to existing loans in PrivateUnsecuredLoanApplicationCreated event for SE.
=> Refinance amount

no/PrivateUnsecuredLoan/schema/PrivateUnsecuredLoanApplicationCreated.yaml, se/PrivateUnsecuredLoan/schema/PrivateUnsecuredLoanApplicationCreated.yaml
Reverted additional properties types for blanco ApplicationCreated schemas
=> Reverted additional properties types

se/PrivateUnsecuredLoan/schema/PrivateUnsecuredLoanOfferAccepted.yaml
Changed OfferAccepted spec to make possibility of attach offer and application details
=> Add extensions to contain app and offer
